[package]
name = "credinform_cli"
version = "0.7.3"
edition = "2021"
authors = ["Viktor Merkurev <mr.fennr@ya.ru>"]
description = "Credinform cli API client"
repository = "https://github.com/fennr/credinform-cli"
keywords = ["credinform", "cli", "api"]
readme = "README.md"

[dependencies]
anyhow = "1.0.100"
base64 = "0.22.1"
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive"] }
log = "0.4.29"
reqwest = { version = "0.12.25", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.8.23"

# debug build for target executable
[profile.dev]
opt-level = 1 # basic optimization to inline iterators and getters
strip = "debuginfo" # strip debug nonsense since debuggers are overrated, remove this to actually do debugging

# debug builds for deps 
[profile.dev.package."*"]
opt-level = 3 # enable full optimization within dependencies - I do not expect to debug my deps
strip = "debuginfo" # strip debug symbols as they are useless with O3 anyway

# debug builds for procmacros
[profile.dev.build-override]
opt-level = 2 # reasonable optimization
codegen-units = 256 # max threading
#debug = false # when possible - this is generally scary as some procmacros will fail without any feedback

# release build for procmacros - same config as debug build for procmacros
[profile.release.build-override]
opt-level = 2
codegen-units = 256
debug = false # when possible
